// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './baloo-chettan-2-487619ee.ttf' with { type: 'url' };
import fullFontUrl from './baloo-chettan-2.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'BalooChettan2 Tegaki 487619ee',
  fullFamily: 'BalooChettan2',
  lineCap: 'round',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'BalooChettan2 Tegaki 487619ee'; src: url(${fontUrl}); } @font-face { font-family: 'BalooChettan2'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1078,
  descender: -392,
  glyphData,
  glyphDataById,
  features: ["akhn","pref","pstf","psts"],
} as const;

export default bundle;
