// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './mandali-20caf0ee.ttf' with { type: 'url' };
import fullFontUrl from './mandali.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Mandali Tegaki 20caf0ee',
  fullFamily: 'Mandali',
  lineCap: 'butt',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'Mandali Tegaki 20caf0ee'; src: url(${fontUrl}); } @font-face { font-family: 'Mandali'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 790,
  ascender: 1087,
  descender: -475,
  glyphData,
  glyphDataById,
  features: ["abvs","blwf","blws","haln"],
} as const;

export default bundle;
