// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './baloo-tamma-2-a437576e.ttf' with { type: 'url' };
import fullFontUrl from './baloo-tamma-2.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'BalooTamma2 Tegaki a437576e',
  fullFamily: 'BalooTamma2',
  lineCap: 'round',
  fontUrl,
  fullFontUrl,
  fontFaceCSS: `@font-face { font-family: 'BalooTamma2 Tegaki a437576e'; src: url(${fontUrl}); } @font-face { font-family: 'BalooTamma2'; src: url(${fullFontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1078,
  descender: -673,
  glyphData,
  glyphDataById,
  features: ["blwf","haln","pres","psts"],
} as const;

export default bundle;
